# Generated by Django 3.0.4 on 2020-04-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200418_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='email',
            field=models.EmailField(default=False, max_length=150),
        ),
        migrations.AddField(
            model_name='blogger',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogger',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
